Repository iammohita/E-commerce, pull requests merged in 2023-02, with the labels that each got.

#1 Extra Files Deleted
  .gitignore
  onlineshop/README.md
  onlineshop/public/favicon.ico
  onlineshop/public/logo192.png
  onlineshop/public/logo512.png
  onlineshop/public/manifest.json
  onlineshop/public/robots.txt
  onlineshop/src/App.css
  onlineshop/src/App.js
  onlineshop/src/App.test.js
  onlineshop/src/index.js
  onlineshop/src/logo.svg
  onlineshop/src/reportWebVitals.js
  onlineshop/src/setupTests.js
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/HomePage.jsx
  src/components/NavBar.jsx
  src/index.css
  src/index.js
Labels: Needs Review ✌

#4 chore: general commit for extra guidance
  jsconfig.json
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  src/App.js
  src/components/ProductCard/ProductCard.scss
  src/components/ProductCard/index.jsx
  src/components/ProductCard/utils.js
  src/components/ProductList/index.jsx
  src/index.css
  src/index.js
  src/styles/fonts/BTITRBD.TTF
  src/styles/randomFile.scss
  src/styles/statics/variables.scss
Labels: enhancement

#5 Get Products' Data From Dummyjson
  package-lock.json
  package.json
  src/App.js
  src/components/ProductList/index.jsx
  src/components/ProductList/requests.js
Labels: Is Reviewed ✨
